import math
import re

def _normalize_text(text: str) -> str:
    """Remove whitespace characters and convert to lowercase."""
    if not text:
        return ""
    return "".join(str(text).lower().split())

def extract_answer_fallback(xml_text: str) -> str:
    """
    Find the answer tag and return the content.
    """
    if not xml_text:
        return ""
    match = re.search(r'<answer>(.*?)</answer>', xml_text, re.IGNORECASE | re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""

def get_mode(answer, marker=None):
    
    if answer.startswith("</think_on>"):
        mode = "should_reasoning"
    elif answer.startswith("</think_off>"):
        mode = "should_direct"
    else:
        raise ValueError("Prompt suffix does not end with expected <think_on> or <think_off> tags.")

    return mode

def get_prompt_suffix(prompt, marker=None):
    if marker is None:
        marker = "<|im_start|>assistant"
    idx = prompt.rfind(marker)

    if idx != -1:
        # Extract everything after the marker (e.g., "\n<think_on>")
        prompt_suffix = prompt[idx + len(marker):].strip()
    else:
        prompt_suffix = ""

    return prompt_suffix

def get_prompt_suffix_and_mode(prompt, marker=None):
    if marker is None:
        marker = "<|im_start|>assistant"
    idx = prompt.rfind(marker)

    if idx != -1:
        # Extract everything after the marker (e.g., "\n<think_on>")
        prompt_suffix = prompt[idx + len(marker):].strip()
    else:
        prompt_suffix = ""

    if prompt_suffix.endswith("<think_on>"):
        mode = "should_reasoning"
    elif prompt_suffix.endswith("<think_off>"):
        mode = "should_direct"
    else:
        raise ValueError("Prompt suffix does not end with expected <think_on> or <think_off> tags.")

    return prompt_suffix, mode

def check_answer_match(pred_norm, gt_norm):
    match = False

    allowed_formats = {
        gt_norm,
        f"option{gt_norm}",
        f"choice{gt_norm}",
        f"answer{gt_norm}",
        f"answer:{gt_norm}",
        f"answeris{gt_norm}",
        f"answeris:{gt_norm}",
        f"theansweris{gt_norm}",
        f"theansweris:{gt_norm}",
        f"finalanswer:{gt_norm}",
        f"finalanswer{gt_norm}",
        f"correctanswer:{gt_norm}",
        f"correctanswer{gt_norm}",
        f"answerchoice{gt_norm}",
        f"selection:{gt_norm}",
        f"selection{gt_norm}",
        f"option:{gt_norm}",
        f"choice:{gt_norm}",
    }

    if pred_norm and gt_norm:
        try:
            pred_num = float(pred_norm)
            gt_num = float(gt_norm)
            if abs(pred_num - gt_num) < 1e-9:
                return True
        except (ValueError, TypeError):
            pass

        if pred_norm == gt_norm:
            match = True
        elif len(gt_norm) == 1 and gt_norm in pred_norm:
            if pred_norm in allowed_formats:
                match = True
    return match

def calculate_length_penalty(think_length, R_penalty_limit, max_len=50, k=0.01):
    """
    Calculates a length-based penalty for the thinking process.

    The penalty logic is defined as:
    - think_length == 0: No penalty (0.0).
    - 1 <= think_length <= max_len: Penalty grows exponentially with length, approaching R_penalty_limit.
    - think_length > max_len: Maximum penalty (R_penalty_limit).

    Args:
        think_length (int): The length of the thinking sequence.
        R_penalty_limit (float): The maximum penalty value.
        max_len (int): The length threshold where the penalty saturates. Defaults to 50.
        k (float): The coefficient controlling the exponential growth rate. Defaults to 0.01.

    Returns:
        float: The calculated penalty score.
    """
    if think_length == 0:
        return 0.0
    elif 1 <= think_length <= max_len:
        return R_penalty_limit * (1 - 0.7 * math.exp(-k * think_length**2))
    else:  # think_length > max_len
        return 1.0 * R_penalty_limit

def stage2_process_completions_for_reward(completion: str, end_token: str = "<|im_end|>") -> str:
    """
    Removes the trailing end token from the completion string if it exists.

    Args:
        completion (str): The completion string generated by the model.
        end_token (str): The end token to look for. Defaults to "<|im_end|>".

    Returns:
        str: The cleaned completion string.
    """
    clean_completion = completion
    if clean_completion.lower().rstrip().endswith(end_token.lower()):
        clean_completion = clean_completion.rstrip()[:-len(end_token)].rstrip()

    # Verify suffix (ensure we are in the correct prompting state)
    clean_completion = "<think_" + (clean_completion if clean_completion else "")

    return clean_completion

def stage1_2_process_completions_for_reward(completions: str, prompt: str) -> str:
    end_tokens = "<|im_end|>"
    if completions.lower().rstrip().endswith(end_tokens.lower()):
        completions = completions.rstrip()[:-len(end_tokens)].rstrip()

    prompt_suffix, mode = get_prompt_suffix_and_mode(prompt, marker=None)
    completion_text = prompt_suffix + (completions if completions else "")
    return mode, prompt_suffix, completion_text
